[package]
name = "folderer"
version = "0.1.0"
authors = ["Justin Sievenpiper <justin@sievenpiper.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.3"
colored = "2.0.0"
